### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by Watanakas** [UbhiTS/ad-calendartvnotifications#1]
The automation does not work for me, I am using it with television sony bravia this is the AppDaemon log, as seen it detects the on, but on the screen no message appears, where the error may be, thank you.

2020-08-30 22:55:52.053830 WARNING calendar_tv_reminders: ------------------------------------------------------------
2020-08-30 22:55:52.052466 WARNING calendar_tv_reminders: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-calendartvreminders/apps/calendar_tv_reminders.py", line 49, in show_notification
    for event in self.calendar_events():
  File "/config/appdaemon/apps/ad-calendartvreminders/apps/calendar_tv_reminders.py", line 60, in calendar_events
    event_message = event["attributes"]["message"]
TypeError: 'NoneType' object is not subscriptable

2020-08-30 22:55:52.050566 WARNING calendar_tv_reminders: ------------------------------------------------------------
2020-08-30 22:55:52.049206 WARNING calendar_tv_reminders: Worker Ags: {'id': '381cafxxxxxxx475da04jkjfkñsdjfkj554', 'name': 'calendar_tv_reminders', 'objectid': '56883e096xxxxxxx36bf5358dfksdljfksdjf43f', 'type': 'scheduler', 'function': >, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'thread-2'}}
2020-08-30 22:55:52.047889 WARNING calendar_tv_reminders: Unexpected error in worker for App calendar_tv_reminders:
2020-08-30 22:55:52.044325 WARNING calendar_tv_reminders: ------------------------------------------------------------
2020-08-30 22:50:57.049953 WARNING calendar_tv_reminders: ------------------------------------------------------------
2020-08-30 22:50:57.047642 WARNING calendar_tv_reminders: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-calendartvreminders/apps/calendar_tv_reminders.py", line 49, in show_notification
    for event in self.calendar_events():
  File "/config/appdaemon/apps/ad-calendartvreminders/apps/calendar_tv_reminders.py", line 60, in calendar_events
    event_message = event["attributes"]["message"]
TypeError: 'NoneType' object is not subscriptable

2020-08-30 22:50:57.045841 WARNING calendar_tv_reminders: ------------------------------------------------------------
2020-08-30 22:50:57.043257 WARNING calendar_tv_reminders: Worker Ags: {'id': '81d5xxxxxxxxxxxxxxxxxxb1a7d731cbf47c27', 'name': 'calendar_tv_reminders', 'objectid': '56883e0xxxxxxxxxxxxxxxxffa5cdcf', 'type': 'scheduler', 'function': >, 'pin_app': True, 'pin_thread': 2, 'kwargs': {'__thread_id': 'thread-2'}}
2020-08-30 22:50:57.041827 WARNING calendar_tv_reminders: Unexpected error in worker for App calendar_tv_reminders:
2020-08-30 22:50:57.038220 WARNING calendar_tv_reminders: ------------------------------------------------------------

**Comment by UbhiTS** [comment]
did you check to see if your TV supports the notifications API ? what's your TV model number ?

**Comment by Watanakas** [comment]
Hi, sorry I was absent my TV model is Sony Bravia KD-55XG80XX manufactured in 2019
