### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by ned786** [UbhiTS/ad-calendartvnotifications#2]
hey, i love this idea but i can not get it to work i get the following log

2021-01-16 13:33:02.033186 WARNING calendar_tv_reminders: ------------------------------------------------------------
2021-01-16 13:33:02.034263 WARNING calendar_tv_reminders: Unexpected error in worker for App calendar_tv_reminders:
2021-01-16 13:33:02.035320 WARNING calendar_tv_reminders: Worker Ags: {'id': 'e1f1b4a7206b42c18d37345d68fe5e3e', 'name': 'calendar_tv_reminders', 'objectid': 'd79bcfc6ac1b467b8c2630f6b8cc4821', 'type': 'scheduler', 'function': <bound method CalendarTVReminders.show_notification of <calendar_tv_reminders.CalendarTVReminders object at 0x7f93845d00>>, 'pin_app': True, 'pin_thread': 1, 'kwargs': {'__thread_id': 'thread-1'}}
2021-01-16 13:33:02.036359 WARNING calendar_tv_reminders: ------------------------------------------------------------
2021-01-16 13:33:02.039299 WARNING calendar_tv_reminders: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 887, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/calendar_tv_reminders.py", line 49, in show_notification
    for event in self.calendar_events():
  File "/config/appdaemon/apps/calendar_tv_reminders.py", line 60, in calendar_events
    event_message = event["attributes"]["message"]
KeyError: 'message'
2021-01-16 13:33:02.040082 WARNING calendar_tv_reminders: ------------------------------------------------------------

**Comment by ned786** [comment]
hey, so i managed to get it working when i imported everything into a google calendar i was using ios before. question, will this give more then one notification if i have 2 events in one day? for example something happening at 12pm and then something else happening at 2pm? or does each event need to pass before it moves onto the next one?

**Comment by UbhiTS** [comment]
hi, as of now, I haven't found a way to display 2 events on the same day as google calendar does not give me that info. I also want that option but right now constrained by the google calendar integration. I use multiple calendars to kind of workaround this, one for birthdays and anniversaries, one for other events like tax payment, insurance reminders etc ...
